#Makefile_lzk

# Created on: 2012-4-11
#     Author: lzk


c_files_lzk=lzk/output_spi.c \
			lzk/fft.c \
			lzk/fileHandler.c \
			lzk/htmlHandler.c \
			lzk/Ascan.c \
			lzk/tofd.c \
			globalData.c 

h_files_lzk=lzk/output_spi.h \
			lzk/fileHandler.h \
			lzk/Ascan.h \
			lzk/common.h \
			lzk/tofd.h \
			globalData.h \
			lzk/fft.h
			
			
-include ui/Makefile
-include uihandler/Makefile
-include map/Makefile
-include string/Makefile