#Makefile

# Created on: 2012-5-3
#     Author: lzk

c_files_lzk +=	net/DopplerNetServer.c \
				net/NetResponseFunc.c \
				net/Operation.c
				
h_files_lzk +=  net/DopplerNetServer.h \
				net/NetResponseFunc.h \
				net/Operation.h