#Makefile

# Created on: 2012-5-3
#     Author: lzk

c_files_lzk +=	uihandler/menu/wizardFoclawHandler.c \
                uihandler/menu/wizardGroupHandler.c \
                uihandler/menu/alarmOutputHandler.c \
                uihandler/menu/updateHandler.c
				
h_files_lzk +=  uihandler/menu/menuDefine.h \
                uihandler/menu/menuHandler.h