#Makefile

# Created on: 2012-5-3
#     Author: lzk

c_files_lzk +=	ui/menu/table.c \
				ui/menu/drawmenu0.c \
				ui/menu/drawmenu1.c \
				ui/menu/drawmenu2.c \
				ui/menu/drawmenu3.c \
				ui/menu/drawmenu4.c \
				ui/menu/drawmenu5.c \
	            ui/menu/menuFunc.c \
	            ui/menu/wizardFocallaw.c \
				ui/menu/wizardGroup.c \
				ui/menu/alarmOutput.c \
				ui/menu/update.c
				
				
h_files_lzk +=  ui/menu/menu.h \
				ui/menu/drawmenu0.h \
				ui/menu/drawmenu1.h \
				ui/menu/drawmenu2.h \
				ui/menu/drawmenu3.h \
				ui/menu/drawmenu4.h \
				ui/menu/drawmenu5.h \
				ui/menu/drawmenu.h \
				ui/menu/menuFunc.h \
				ui/menu/table.h