#Makefile

# Created on: 2012-5-3
#     Author: lzk

c_files_lzk +=	ui/dialog.c \
				ui/keyboard.c \
				ui/labelButton.c \
				ui/help.c \
				ui/workpiece.c \
				ui/draw_overlay.c \
				ui/authorization.c
				
h_files_lzk +=  ui/labelbutton.h \
				ui/ui.h \
				ui/workpiece.h \
				ui/draw_overlay.h \
				ui/authorization.h
				
-include ui/menu/Makefile
-include ui/dialog/Makefile
-include ui/picbuf_inline/Makefile
