#calculation direction include file list
#header_files += calculation/getMeasureData.h 
#
#source_files += calculation/getMeasureData.c 
#
header_files += calculation/getMeasureData.h \
                calculation/sizingcurve.h \
                calculation/limit.h

source_files += calculation/getMeasureData.c \
                calculation/sizingcurve.c \
				calculation/limit.c