#Makefile

# Created on: 2012-5-3
#     Author: lzk

c_files_lzk +=	ui/picbuf_inline/picbuf_inline.c 				
				
h_files_lzk +=  ui/picbuf_inline/pic_black25.h \
				ui/picbuf_inline/pic_clock.h \
				ui/picbuf_inline/pic_file_name40.h \
				ui/picbuf_inline/pic_gear.h \
				ui/picbuf_inline/pic_snow.h \
				ui/picbuf_inline/pic_tt.h \
				ui/picbuf_inline/pic00.h \
				ui/picbuf_inline/pic01.h \
				ui/picbuf_inline/pic02.h \
				ui/picbuf_inline/pic10.h \
				ui/picbuf_inline/pic11.h \
				ui/picbuf_inline/pic12.h \
				ui/picbuf_inline/pic20.h \
				ui/picbuf_inline/pic21.h \
				ui/picbuf_inline/pic22.h \
				ui/picbuf_inline/pic30.h \
				ui/picbuf_inline/pic31.h \
				ui/picbuf_inline/pic311.h \
				ui/picbuf_inline/pic32.h \
				ui/picbuf_inline/pic322.h