#Makefile

# Created on: 2012-5-3
#     Author: lzk

c_files_lzk +=	ui/dialog/filelistDialog.c \
				ui/dialog/baseDialog.c \
				ui/dialog/filelistScroll.c \
				ui/dialog/fileManage.c \
				ui/dialog/fileOpen.c \
				ui/dialog/saveSetupAs.c \
				ui/dialog/tableExport.c \
				ui/dialog/probeDialog.c \
				ui/dialog/reportPreview.c
				
h_files_lzk +=  ui/dialog/filelist.h 