#Makefile

# Created on: 2012-5-3
#     Author: lzk

c_files_lzk +=	threads/threadDrawData.c \
                threads/threadRefresh.c \
                threads/threads.c
	
				
h_files_lzk +=  threads/threadDrawData.h \
		        threads/threadRefresh.h \
		        threads/threads.h

