#Makefile

# Created on: 2012-5-3
#     Author: lzk

c_files_lzk +=	uihandler/handler.c \
				uihandler/keyHandler.c 
				
h_files_lzk +=  uihandler/handler.h \
				uihandler/keyHandler.h

-include uihandler/menu/Makefile