/*
 * commonString.h
 *
 *  Created on: 2012-7-16
 *      Author: lzk
 */

#ifndef COMMONSTRINGDICT_H_
#define COMMONSTRINGDICT_H_

#include "language.h"

static const char* tmpHtmlDict[] =
{
		"File Name:" ,"File Size:","Save Time:" ,"Generated by Software Version:" ,"Generated by Module:"
		,"Note:" ,"Head:" ,"Channel Quantity:"
};

static const char* unit_dict[] =
{
		"" ,"(mm)" ,"(in)" ,"(°)" ,"(ms)" ,"(μs)" ,"(ns)" ,"(s)"
};


static const char* dataPath_dict[] =
{


#if  0
		/*DATA_PATH_SETUP,*/			"/media/card/config/setup/", //setup
		/*DATA_PATH_DATA,*/				"/media/card/data/InspectData/", //data
		/*DATA_PATH_REPORT,*/			"/media/card/data/Report/", //report
		/*DATA_PATH_PICTURE,*/			"/media/card/data/Image/",//picture
        /*DATA_PATH_CAD,*/				"/media/card/data/Part/",
		/*DATA_PATH_USB,*/				"/opt/usbStorage/",//usb
		/*DATA_PATH_SETUP_SAMPLE,*/		"/home/tt/",//setup sample path
		/*DATA_PATH_DATA_SAMPLE,*/		"/home/tt/TT/",//data sample path
#else
		/*DATA_PATH_SETUP,*/			"/home/tt/TT/source/user/setup/", //setup
		/*DATA_PATH_DATA,*/				"/home/tt/TT/data/InspectData/", //data
		/*DATA_PATH_REPORT,*/			"/home/tt/TT/data/Report/", //report
		/*DATA_PATH_PICTURE,*/			"/home/tt/TT/data/Image/",//picture
        /*DATA_PATH_CAD,*/				"/home/tt/TT/data/Part/",   //CAD
		/*DATA_PATH_USB,*/				"/opt/usbStorage/",//usb
		/*DATA_PATH_SETUP_SAMPLE,*/		"/home/tt/",//setup sample path
		/*DATA_PATH_DATA_SAMPLE,*/		"/home/tt/TT/",//data sample path
#endif
	/*DATA_PATH_MAX,*/
};


static const char* dataSuffix_dict[] =
{
		/*DATA_SUFFIX_SETUP,*/		".cfg", //setup
		/*DATA_SUFFIX_DATA,*/		".data", //data
		/*DATA_SUFFIX_REPORT,*/		".html", //report
		/*DATA_SUFFIX_PICTURE,*/	".jpg", //picture
        /*DATA_SUFFIX_CAD,*/        ".dxf", //CAD
		/*DATA_SUFFIX_ALL,*/		"",//all

		/*DATA_SUFFIX_MAX,*/
};

static const stringStruct commonString[] =
{
/*COMMONSTRING_TMP_HTML*/				{tmpHtmlDict 			,NUM_OF_STRING(tmpHtmlDict)},
/*COMMONSTRING_UNIT*/					{unit_dict				,NUM_OF_STRING(unit_dict)},
/*COMMONSTRING_DATA_PATH*/				{dataPath_dict			,NUM_OF_STRING(dataPath_dict)},
/*COMMONSTRING_DATA_SUFFIX*/			{dataSuffix_dict 		,NUM_OF_STRING(dataSuffix_dict)},

/*COMMONSTRING_MAX*/
};

#endif /* COMMONSTRINGDICT_H_ */
