#Makefile

# Created on: 2012-5-3
#     Author: lzk

c_files_lzk +=	string/_string.c \
                string/getFieldString.c
				
h_files_lzk +=  string/_string.h \
 				string/language_d.h \
 				string/language.h \
 				string/labelDict.h \
 				string/languageDict.h \
 				string/mainStringDict.h \
 				string/reportStringDict.h \
 				string/string_d.h \
 				string/commonStringDict.h \
 				string/getFieldString.h \
 				string/dialog_str.h
 				