#Makefile

# Created on: 2012-5-3
#     Author: lzk

c_files_lzk +=	map/menu3Map.c \
				map/menu4DataMap.c \
 				map/menuMap.c \
				
				
h_files_lzk +=  map/menuMap.h \
 				map/menuDataMap.h \
 				map/popDataMap.h \
 				map/spinDataMap.h