/*
 * popDataMap.h
 *
 *  Created on: 2012-5-24
 *      Author: gener
 */

#ifndef POPDATAMAP_H_
#define POPDATAMAP_H_

#include "../uihandler/menu/menuDefine.h"
#include "../string/_string.h"

enum
{
		//group向导
	POPDATA_GROUP_SELECT,//		{0 ,0 ,0 ,0},//0  //group select
	POPDATA_GEOMETRY,//			{0 ,0 ,0 ,0},//1  //geometry
	POPDATA_GROUP_MODE,//			{0 ,0 ,0 ,0},//2  //group mode
	POPDATA_TR_MODE,//				{0 ,0 ,0 ,0},//3  //tx rx mode
	POPDATA_PE_SELECT_PROBE,//		{0 ,0 ,0 ,0},//4  //pe selece probe
	POPDATA_PE_SELECT_WEDGE,//		{0 ,0 ,0 ,0},//5  //pe selece wedge
	POPDATA_SELECT_PROBE,//		{0 ,0 ,0 ,0},//6  //select probe
	POPDATA_SELECT_WEDGE,//		{0 ,0 ,0 ,0},//7	//pe selece wedge
	POPDATA_SOURCE,//				{0 ,0 ,0 ,0},//8  //source
	POPDATA_MATERIAL,//			{0 ,0 ,0 ,0},//9  //material
		//focal law向导
	POPDATA_FOCAL_GROUP_SELECT,//	{0 ,0 ,0 ,0},//10 //group select
	POPDATA_LAW_TYPE,//					{0 ,0 ,0 ,0},//11 //law
	POPDATA_FOCAL_TYPE,//			{0 ,0 ,0 ,0},//12	//focal type
	POPDATA_WAVE_TYPE,//			{0 ,0 ,0 ,0},//13	//wave type
	//alarm 210
	POPDATA_ALARM,//				{0 ,0 ,0 ,0},//15 //alarm 210
	POPDATA_ALARM_GROUP_SELECT1,//	{0 ,0 ,0 ,0},//16 //group select
	POPDATA_ALARM_GROUP_SELECT2,//	{0 ,0 ,0 ,0},//17 //group select
	POPDATA_ALARM_GROUP_SELECT3,//	{0 ,0 ,0 ,0},//18 //group select
	POPDATA_CONDITION11,//			{0 ,0 ,0 ,0},//19 //condition1
	POPDATA_CONDITION12,//			{0 ,0 ,0 ,0},//20 //condition1
	POPDATA_CONDITION13,//			{0 ,0 ,0 ,0},//21 //condition1
	POPDATA_OPERATOR1,//			{0 ,0 ,0 ,0},//22 //operator
	POPDATA_OPERATOR2,//			{0 ,0 ,0 ,0},//23 //operator
	POPDATA_OPERATOR3,//			{0 ,0 ,0 ,0},//24 //operator
	POPDATA_CONDITION21,//			{0 ,0 ,0 ,0},//25 //condition2
	POPDATA_CONDITION22,//			{0 ,0 ,0 ,0},//26 //condition2
	POPDATA_CONDITION23,//			{0 ,0 ,0 ,0},//27 //condition2
	//output 220
	POPDATA_OUTPUT,//				{0 ,0 ,0 ,0},//28 //output 220
	POPDATA_ANALOG_GROUP1,//		{0 ,0 ,0 ,0},//29 //analog group
	POPDATA_ANALOG_GROUP2,//		{0 ,0 ,0 ,0},//30 //analog group
	POPDATA_SOUND,//				{0 ,0 ,0 ,0},//31 //sound
	POPDATA_ANALOG_DATA1,//		{0 ,0 ,0 ,0},//32 //analog data
	POPDATA_ANALOG_DATA2,//		{0 ,0 ,0 ,0},//33 //analog data

	POPDATA_MAX,//

};
#define popDataAddress(index) (popDataDict + (index))

static popDataStruct popDataDict[] =
{
								//group向导
/*POPDATA_GROUP_SELECT*/		{MAINSTRINGDICT_GROUP 			,MAINSTRINGDICT_ADD 			,0 ,0},
/*POPDATA_GEOMETRY*/			{MAINSTRINGDICT_GEOMETRY 		,MAINSTRINGDICT_GEOMETRY 		,0x8 ,0},
/*POPDATA_GROUP_MODE*/			{MAINSTRINGDICT_GROUP_MODE 		,MAINSTRINGDICT_S_GROUP_MODE 	,0 ,0},
/*POPDATA_TR_MODE*/				{MAINSTRINGDICT_TR_MODE 		,MAINSTRINGDICT_S_TR_MODE 		,0 ,0},
/*POPDATA_PE_SELECT_PROBE*/		{MAINSTRINGDICT_PE_SELECT_PROBE ,MAINSTRINGDICT_PE_SELECT_PROBE ,0 ,0},
/*POPDATA_PE_SELECT_WEDGE*/		{MAINSTRINGDICT_PE_SELECT_PROBE ,MAINSTRINGDICT_PE_SELECT_PROBE ,0 ,0},
/*POPDATA_SELECT_PROBE*/		{MAINSTRINGDICT_SELECT_PROBE 	,MAINSTRINGDICT_SELECT_PROBE 	,0x2 ,0},
/*POPDATA_SELECT_WEDGE*/		{MAINSTRINGDICT_SELECT_PROBE 	,MAINSTRINGDICT_SELECT_PROBE 	,0x2 ,0},
/*POPDATA_SOURCE*/				{MAINSTRINGDICT_GROUP 			,MAINSTRINGDICT_NOCOPY 			,0 ,0},
/*POPDATA_MATERIAL*/			{MAINSTRINGDICT_MATERIAL 		,MAINSTRINGDICT_MATERIAL 		,0 ,0},
								//focal law向导
/*POPDATA_FOCAL_GROUP_SELECT*/	{MAINSTRINGDICT_GROUP 			,MAINSTRINGDICT_GROUP 			,0 ,0},
/*POPDATA_LAW_TYPE*/			{MAINSTRINGDICT_LAW_TYPE 		,MAINSTRINGDICT_S_LAW_TYPE 		,0 ,0},
/*POPDATA_FOCAL_TYPE*/			{MAINSTRINGDICT_FOCAL_TYPE 		,MAINSTRINGDICT_FOCAL_TYPE 		,0 ,0},
/*POPDATA_WAVE_TYPE*/			{MAINSTRINGDICT_WAVE_TYPE 		,MAINSTRINGDICT_S_WAVE_TYPE 	,0 ,0},
								//alarm 210
/*POPDATA_ALARM*/				{MAINSTRINGDICT_OUTPUT 			,MAINSTRINGDICT_OUTPUT 			,0 ,0},
/*POPDATA_ALARM_GROUP_SELECT1*/	{MAINSTRINGDICT_GROUP 			,MAINSTRINGDICT_GROUP_SELECT 	,0 ,0},
/*POPDATA_ALARM_GROUP_SELECT2*/	{MAINSTRINGDICT_GROUP 			,MAINSTRINGDICT_GROUP_SELECT 	,0 ,0},
/*POPDATA_ALARM_GROUP_SELECT3*/	{MAINSTRINGDICT_GROUP 			,MAINSTRINGDICT_GROUP_SELECT 	,0 ,0},
/*POPDATA_CONDITION11*/			{MAINSTRINGDICT_CONDITION 		,MAINSTRINGDICT_CONDITION 		,0 ,0},
/*POPDATA_CONDITION12*/			{MAINSTRINGDICT_CONDITION 		,MAINSTRINGDICT_CONDITION 		,0 ,0},
/*POPDATA_CONDITION13*/			{MAINSTRINGDICT_CONDITION 		,MAINSTRINGDICT_CONDITION 		,0 ,0},
/*POPDATA_OPERATOR1*/			{MAINSTRINGDICT_OPERATOR 		,MAINSTRINGDICT_OPERATOR 		,0 ,0},
/*POPDATA_OPERATOR2*/			{MAINSTRINGDICT_OPERATOR 		,MAINSTRINGDICT_OPERATOR 		,0 ,0},
/*POPDATA_OPERATOR3*/			{MAINSTRINGDICT_OPERATOR 		,MAINSTRINGDICT_OPERATOR 		,0 ,0},
/*POPDATA_CONDITION21*/			{MAINSTRINGDICT_CONDITION 		,MAINSTRINGDICT_CONDITION 		,0 ,0},
/*POPDATA_CONDITION22*/			{MAINSTRINGDICT_CONDITION 		,MAINSTRINGDICT_CONDITION 		,0 ,0},
/*POPDATA_CONDITION23*/			{MAINSTRINGDICT_CONDITION 		,MAINSTRINGDICT_CONDITION 		,0 ,0},
								//output 220
/*POPDATA_OUTPUT*/				{MAINSTRINGDICT_OUTPUT 			,MAINSTRINGDICT_OUTPUT 			,0 ,0},
/*POPDATA_ANALOG_GROUP1*/		{MAINSTRINGDICT_GROUP 			,MAINSTRINGDICT_GROUP 			,0 ,0},
/*POPDATA_ANALOG_GROUP2*/		{MAINSTRINGDICT_GROUP 			,MAINSTRINGDICT_GROUP 			,0 ,0},
/*POPDATA_SOUND*/				{MAINSTRINGDICT_SOUND 			,MAINSTRINGDICT_S_SOUND 		,0 ,0},
/*POPDATA_ANALOG_DATA1*/		{MAINSTRINGDICT_ANALOG_DATA 	,MAINSTRINGDICT_ANALOG_DATA 	,0 ,0},
/*POPDATA_ANALOG_DATA2*/		{MAINSTRINGDICT_ANALOG_DATA 	,MAINSTRINGDICT_ANALOG_DATA 	,0 ,0},

/*POPDATA_MAX*/
};

#endif /* POPDATAMAP_H_ */
